main: ink.pmc.common.deploader.DepLoaderPlugin
name: common-dependency-loader
version: ${version}
api-version: ${api}
folia-supported: true
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0-Beta4
  - com.squareup.okhttp3:okhttp:5.0.0-alpha.12
  - com.google.code.gson:gson:2.10.1
  - org.mongodb:mongodb-driver-kotlin-coroutine:5.0.1
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.catppuccin:catppuccin-palette:1.0.0
  - org.incendo:cloud-paper:2.0.0-beta.5
  - org.incendo:cloud-kotlin-coroutines:2.0.0-beta.4
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0
  - com.electronwill.night-config:core:3.6.0
  - com.electronwill.night-config:toml:3.6.0
  - io.netty:netty-all:4.1.109.Final
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.15.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.15.0