main: ink.pmc.common.deploader.DepLoaderPlugin
name: common-dependency-loader
version: ${version}
api-version: ${api}
folia-supported: true
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0-Beta4
  - com.squareup.okhttp3:okhttp:5.0.0-alpha.12
  - com.google.code.gson:gson:2.10.1
  - org.mongojack:mongojack:4.8.2
  - org.mongodb:mongodb-driver-sync:4.11.1
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.catppuccin:catppuccin-palette:1.0.0
  - org.incendo:cloud-paper:2.0.0-beta.2
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0