[versions]
kotlin = "1.9.24"
kotlinx-coroutine = "1.8.0"
bukkit = "1.20"
nightconfig = "3.6.7"
mccoroutine = "2.15.0"
bytebuddy = "1.14.14"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutine" }
paper-api = { module = "io.papermc.paper:paper-api", version = "1.20.4-R0.1-SNAPSHOT" }
velocity-api = { module = "com.velocitypowered:velocity-api", version = "3.3.0-SNAPSHOT" }
velocity = { module = "com.velocitypowered:velocity", version = "3.3.0-379" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.12" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
mongodb = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version = "5.0.1" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.8" }
catppuccin = { module = "com.catppuccin:catppuccin-palette", version = "1.0.0" }
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }
cloud-paper = { module = "org.incendo:cloud-paper", version = "2.0.0-beta.5" }
cloud-velocity = { module = "org.incendo:cloud-velocity", version = "2.0.0-beta.2" }
cloud-coroutines = { module = "org.incendo:cloud-kotlin-coroutines", version = "2.0.0-beta.4" }
netty = { module = "io.netty:netty-all", version = "4.1.109.Final" }
mccoroutine-bukkit-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-bukkit-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core", version.ref = "mccoroutine" }
mccoroutine-velocity-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-api", version.ref = "mccoroutine" }
mccoroutine-velocity-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-core", version.ref = "mccoroutine" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
jsoup = { module = "org.jsoup:jsoup", version = "1.17.2" }
protocolize = { module = "dev.simplix:protocolize-api", version = "2.3.3" }
protocollib = { module = "com.comphenix.protocol:ProtocolLib", version = "5.1.0" }
spark-api = { module = "me.lucko:spark-api", version = "0.1-SNAPSHOT" }

[bundles]
kotlin = ["kotlin-stdlib", "kotlinx-coroutine-core"]
nightconfig = ["nightconfig-core", "nightconfig-toml"]
cloud = ["cloud-paper", "cloud-velocity", "cloud-coroutines"]
mccoroutine = ["mccoroutine-bukkit-api", "mccoroutine-bukkit-core", "mccoroutine-velocity-api", "mccoroutine-velocity-core"]
bytebuddy = ["bytebuddy", "bytebuddy-agent"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.4" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }