main: ink.pmc.common.bedrockadaptive.PaperBedrockAdaptivePlugin
name: common-bedrock-adaptive
version: ${version}
api-version: ${api}
folia-supported: true
depend:
  - common-dependency-loader
  - common-utils
  - common-member
  - floodgate
  - ProtocolLib