main: ink.pmc.common.exchange.PaperExchangePlugin
name: common-exchange
version: ${version}
api-version: ${api}
folia-supported: true
depend:
  - common-dependency-loader
  - common-utils
  - common-member