main: ink.pmc.common.member.paper.PaperMemberPlugin
name: common-member
version: ${version}
api-version: ${api}
folia-supported: true
softdepend:
  - floodgate
depend:
  - common-dependency-loader
  - common-utils
  - common-rpc