chunk-preserve-radius = -1
cache-interval = 100
cooldown = "60s"
gray-test {
  enabled = false
  cooldown = "300s"
  default-cost = 10.0
  world-costs {}
  existing-players-enabled = false
  existing-players-percentage = 0
}
default {
  spawnpoint-as-center = true
  center {
    x = 0.0
    z = 0.0
  }
  cache-amount = 10
  start-radius = 0
  end-radius = 10000
  max-height = -1
  min-height = -1
  no-cover = true
  max-attempts = 5
  cost = 0.0
  blacklisted-biomes = []
}
worlds {
  world {
    max-height = 192
    min-height = 63
  }
  world_nether {
    max-height = 125
    min-height = 5
  }
  world_the_end {
    max-height = 256
    min-height = 0
  }
}
enabled-worlds = ["world"]
