image {
  map-id-range {
    start = 100000000
    end = 100499999
  }
  max-name-length = 20
  max-images-per-player = 20
}

upload {
  request-expire-after = 10m
  max-bytes = 10485760
  max-width = 4096
  max-height = 4096
  max-pixels = 16777216
  min-short-edge = 16
  min-pixels = 256
  max-aspect-ratio = 8.0
  allowed-file-extensions = ["png", "jpg", "jpeg", "webp", "gif"]
  supported-format-names = ["PNG", "JPEG", "WebP", "GIF"]
  temp-folder = "/temp/plutoproject_gallery_$id"
  base-url = "https://gallery.plutoproject.club/"
  port = 24213
}

decode {
  max-parallel-tasks = 2
  max-bytes = 10485760
  max-pixels = 16777216
  max-frames = 200
}

render {
  max-parallel-tasks = 4
  default-reposition-mode = CONTAIN
  default-scale-mode = BILINEAR
  default-quantize-mode = RGB565
  default-dither-mode = FLOYD_STEINBERG
}

display {
  static {
    update-interval = 50ms
  }
  animated {
    max-frames-per-second = 20
  }
  visible-distance = 64.0
}

send {
  max-queue-size = 256
  max-updates-in-span = 10
  update-limit-span = 50ms
}
