image {
  map-id-range {
    start = 100000000
    end = 100499999
  }
  max-name-length = 20
  max-images-per-player = 20
  max-map-blocks = 16
  static-max-map-blocks = null
  animated-max-map-blocks = 1
  max-long-edge-blocks = 8
}

file-processing {
  max-bytes = 10485760
  max-pixels = 16777216
  max-frames = 200
  temp-folder = "/tmp/"
}

upload {
  request-expire-after = 5m
  request-remove-after = 10m
  base-url = "https://gallery.plutoproject.club/"
  port = 24213
  suggested-max-width = 4096
  suggested-max-height = 4096
}

decode {
  max-parallel-tasks = 2
}

render {
  max-parallel-tasks = 4
  reposition-mode = CONTAIN
  scale-mode = BILINEAR
  quantize-mode = RGB565
  dither-mode = FLOYD_STEINBERG
}

display {
  static {
    update-interval = 50ms
  }
  animated {
    max-frames-per-second = 10
  }
  visible-distance = 32.0
}

send {
  max-queue-size = 256
  max-updates-in-span = 1
  update-limit-span = 100ms
}
